### ISSUE TITLE
Register individual items as part of a Set

### ISSUE THREAD

**Issue by vinivasq** [vinivasq/seamstress-frontend#51]
- [ ] Refactor item register as a reusable component

### Todo's Sets
- [ ] Allow set selection only at primary item component
- [ ] The name of the model will be the same as the set itself if a set is selected and is a primary item, blocking the name field.
- [ ] Show "Add Piece" button if the primary item has s Set selected.
- [ ] Inherit the attributes from the primary item on each individual pieces.
- [ ] Allow measures to be informed only at individual pieces of a Set or if the main item is not a Set
- [ ] Require to create at least 1 individual item if the primary as a Set
- [ ] Show warning dialog when only 1 individual item is informed for a Set (since is doesn't makes much sense to create a Set that only has 1 item)
